/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdcbd",
        "secondary-fixed": "#ffddaf",
        outline: "#3b82f6",
        "on-surface-variant": "#94a3b8",
        "secondary-fixed-dim": "#ffba43",
        "on-primary-container": "#1e3a8a",
        "on-error": "#690005",
        "on-background": "#e3e2e2",
        "inverse-primary": "#1d4ed8",
        "on-secondary-container": "#694600",
        secondary: "#ffd393",
        tertiary: "#fff8f4",
        "surface-dim": "#0a0a0c",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#2c1701",
        "inverse-surface": "#e3e2e2",
        "error-container": "#93000a",
        "inverse-on-surface": "#2f3131",
        "surface-container-lowest": "#050506",
        background: "#0a0a0c",
        "on-secondary-fixed-variant": "#614000",
        "on-tertiary": "#442b10",
        "on-secondary-fixed": "#281800",
        "surface-container": "#111827",
        "primary-container": "#3b82f6",
        "tertiary-fixed-dim": "#e7bf99",
        "tertiary-container": "#ffd5ae",
        "surface-container-highest": "#1f2937",
        surface: "#0a0a0c",
        "on-tertiary-fixed-variant": "#5d4124",
        "on-tertiary-container": "#7a5b3c",
        "primary-fixed": "#93c5fd",
        "on-primary-fixed": "#172554",
        "on-primary-fixed-variant": "#1e40af",
        "surface-container-low": "#0f172a",
        "outline-variant": "#1e293b",
        "on-surface": "#e3e2e2",
        "surface-bright": "#1e293b",
        "surface-container-high": "#1e293b",
        "primary-fixed-dim": "#3b82f6",
        "on-primary": "#ffffff",
        primary: "#3b82f6",
        "surface-tint": "#3b82f6",
        "secondary-container": "#fdaf00",
        "on-secondary": "#432c00",
        "on-error-container": "#ffdad6",
        "surface-variant": "#1e293b",
      },
      fontFamily: {
        mono: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "code-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
      spacing: {
        base_unit: "8px",
        margin_sm: "24px",
        gutter: "1px",
        margin_lg: "48px",
        container_max: "1440px",
      },
    },
  },
  plugins: [],
};
